video_path: videos/my_road.mp4
model_path: model/yolov10l.pt
classes:
- car
- bus
- truck
- motorcycle
tracker_type: deepsort
zones:
- name: Z1
  points:
  - - 1850
    - 792
  - - 1
    - 704
  - - 751
    - 624
  - - 1630
    - 703
- name: Z2
  points:
  - - 783
    - 617
  - - 948
    - 590
  - - 819
    - 526
  - - 758
    - 552
- name: Z3
  points:
  - - 939
    - 601
  - - 1362
    - 650
  - - 1129
    - 551
  - - 1021
    - 539
skip_frame: 1
show_fps: true
save_csv: results/counts.csv
save_video: results/annotated.mp4
