video_path: videos/night.mp4
model_path: yolov8l.pt
classes: [car, bus, truck, motorcycle]
tracker_type: deepsort            # deepsort 或 sort

routes:
  - name: route1
    entry:
      p1:
      - 766
      - 589
      p2:
      - 1115
      - 615
    exit:
      p1:
      - 432
      - 648
      p2:
      - 1046
      - 721
  - name: route2
    entry:
      p1:
      - 1195
      - 914
      p2:
      - 1911
      - 808
    exit:
      p1:
      - 1194
      - 683
      p2:
      - 1489
      - 674

skip_frame: 1                     # 每 N+1 幀做一次偵測
show_fps: true
save_csv: results/night_counts.csv
save_video: results/night_annotated.mp4
